---
- name: Installation pre-requis pour grafana-server
  apt:
    update_cache: yes
    pkg:
      - apt-transport-https
      - software-properties-common
      - wget

- name: Creation du dossier pour les cles GPG
  ansible.builtin.file:
    path: /etc/apt/keyrings/
    state: directory

- name: Ajout de la cle GPG Grafana
  apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: Ajout du depot Grafana
  ansible.builtin.apt_repository:
    repo: 'deb https://apt.grafana.com stable main'
    state: present
    update_cache: yes

- name: Installation Grafana OSS
  apt:
    update_cache: yes
    pkg:
      - grafana

- name: Activation et lancement grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes