- hosts: opnsense
  connection: local
  gather_facts: no
  module_defaults:
    group/ansibleguy.opnsense.all:
      firewall: '10.10.61.254'
      api_credential_file: './secret/opnsenseapikey.txt'
      ssl_verify: false

    ansibleguy.opnsense.source_nat:
      match_fields: ['description']

    ansibleguy.opnsense.list:
      target: 'source_nat'

  tasks:
    - name: Ajouter une règle NAT
      ansibleguy.opnsense.source_nat:
        description: 'grafana'
        match_fields: ['description']
        interface: 'wan'
        ip_protocol: 'inet'
        protocol: 'TCP'
        source_invert: false
        source_net: '192.168.0.252'
        source_port: '3000'
        destination_invert: false
        destination_net: '10.10.60.10'
        destination_port: '3000'
        target: '10.10.60.10'
        target_port: '3000'
        log: true
        state: 'present'
        enabled: true
