- hosts: proxy
  gather_facts: yes
  become: yes
  roles:
    - role: proxy

- hosts: keepalived_master
  gather_facts: yes
  become: yes
  roles:
    - role: keepalived/master

- hosts: keepalived_backup
  gather_facts: yes
  become: yes
  roles:
    - role: keepalived/backup