- hosts: loki
  gather_facts: yes
  become: yes
  roles:
    - role: loki
  
- hosts: grafana
  gather_facts: yes
  become: yes
  roles:
    - role: grafana

- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: promtail