- hosts: wazuh-dashboard
  gather_facts: yes
  become: yes
  roles:
    - role: wazuh-dashboard

- hosts: wazuh-indexer
  gather_facts: yes
  become: yes
  roles:
    - role: wazuh-indexer

- hosts: wazuh-server
  gather_facts: yes
  become: yes
  roles:
    - role: wazuh-server