---
- name: Installation unzip
  ansible.builtin.package:
    name:
      - unzip
    state: present
    
- name: Telecharge & decompresse loki-linux-amd64.zip
  ansible.builtin.unarchive:
    src: https://github.com/grafana/loki/releases/download/v2.8.7/promtail-linux-amd64.zip
    dest: /usr/local/bin/
    remote_src: yes

- name: Ajout droit +x sur /usr/local/bin/promtail-linux-amd64
  file:
    path: /usr/local/bin/promtail-linux-amd64
    state: file
    owner: root
    group: root
    mode: 0755

- name: Creation dossier /etc/promtail
  ansible.builtin.file:
    path: /etc/promtail
    state: directory

- name: Vérification si configuration promtail.yml existe
  stat:
    path: '/etc/promtail/promtail.yml'
  register: check_promtail

- name: Copie de la configuration promtail.yml
  template:
    src: "{{ item.src }}"
    dest: '/etc/promtail/promtail.yml'
  when: check_promtail.stat.exists == False

- name: Verification si une configuration systemd promtail.service existe
  stat:
    path: '/etc/systemd/system/promtail.service'
  register: check_promtail_systemd

- name: Copie de la configuration systemd
  template:
    src: roles/promtail/templates/promtail.service
    dest: /etc/systemd/system/promtail.service
  when: check_promtail_systemd.stat.exists == False

- name: Recharge systemd daemons
  systemd:
    daemon_reload: yes

- name: Lancement Promtail
  systemd:
    name: promtail
    state: started

- name: Activation Promtail
  systemd:
    name: promtail
    enabled: yes