- name: Verification si configuration promtail.yml existe - Apache
  stat:
    path: '/etc/promtail/promtail.yml'
  register: check_promtail_apache

- name: Copie de la confiuration promtail.yml
  template:
    src: roles/promtail/templates/promtail-apache.yml.j2
    dest: /etc/promtail/promtail.yml
  when: "'web' in group_names and check_promtail_apache.stat.exists == False"

- name: Verification si configuration promtail.yml existe - HAPROXY
  stat:
    path: '/etc/promtail/promtail.yml'
  register: check_promtail_haproxy

- name: Copie de la confiuration promtail.yml
  template:
    src: roles/promtail/templates/promtail-haproxy.yml.j2
    dest: /etc/promtail/promtail.yml
  when: "'proxy' in group_names and check_promtail_haproxy.stat.exists == False"

- name: Verification si configuration promtail.yml existe - ALL
  stat:
    path: '/etc/promtail/promtail.yml'
  register: check_promtail_all

- name: Copie de la confiuration promtail.yml
  template:
    src: roles/promtail/templates/promtail.yml.j2
    dest: /etc/promtail/promtail.yml
  when: "'proxy' not in group_names and 'web' not in group_names and check_promtail_all.stat.exists == False"