---
- name: Install nfs server and LVM packages
  apt:
    name: nfs-kernel-server lvm2
    state: latest 

- name: Create physical volume
  command: pvcreate /dev/sdb

- name: Create volume group
  command: vgcreate vg_nfs /dev/sdb

- name: Create logical volume
  command: lvcreate -l 100%FREE -n lv_nfs vg_nfs

- name: Create filesystem on logical volume
  filesystem:
    fstype: ext4
    dev: /dev/vg_nfs/lv_nfs

- name: Create directory /srv/nfs
  file:
    path: /srv/nfs
    state: directory
    mode: '0755'

- name: Mount logical volume in /srv/nfs
  mount:
    path: /srv/nfs
    src: /dev/vg_nfs/lv_nfs
    fstype: ext4
    state: mounted

- name: Export directory to subnet front / back
  lineinfile:
    path: /etc/exports
    regex: '^/srv/nfs.*$'
    line: '/srv/nfs 10.10.60.0/23(rw,sync,no_subtree_check,no_root_squash,anonuid=33,anongid=33)'

- name: Export filesystems
  command: exportfs -a

- name: Check Kanboard directory existence
  stat:
    path: /srv/nfs/kanboard
  register: kanboardinstall

- name: Download Kanboard archive
  unarchive:
    src: https://github.com/kanboard/kanboard/archive/refs/tags/v1.2.34.tar.gz
    dest: /srv/nfs/
    remote_src: yes
  when: not kanboardinstall.stat.exists