---
- name: Installation prre-requis pour grafana-server
  apt:
    update_cache: yes
    pkg:
      - apt-transport-https
      - software-properties-common
      - wget

- name: Creation du dossier pour les cles GPG
  ansible.builtin.file:
    path: /etc/apt/keyrings/
    state: directory

- name: Telechargement de la cle GPG Grafana
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /etc/apt/keyrings/grafana.gpg
    mode: '0644'
    force: true

- name: Ajout du depot Grafana
  ansible.builtin.apt_repository:
    filename: example-repo
    repo: 'deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main'

- name: Installation Grafana OSS
  apt:
    update_cache: yes
    pkg:
      - grafana

- name: Recharge systemd daemons
  systemd:
    daemon_reload: yes

- name: Activation et lancement grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes
  when: ansible_facts.services['grafana-server.service'] is defined and ansible_facts.services['grafana-server.service'].state != 'running'